#!/bin/bash

# Define color variables
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Iterate over each item in the current directory
for dir in */ ; do
    # Check if the item is a directory
    if [ -d "$dir" ]; then
        cd "$dir"  # Enter the directory
        if [ -d ".git" ]; then  # Check if it is a git repository
            repo_name=$(basename "$dir")
            branch_name=$(git rev-parse --abbrev-ref HEAD)
            echo -e "Pulling in ${BLUE}${repo_name}${NC} on branch ${GREEN}${branch_name}${NC}"
            git pull  # Perform the git pull
        else
            echo "Skipping directory $dir - not a git repository"
        fi
        cd ..  # Return to the parent directory
    fi
done